Alpha = {}
Animation = {}
AnimationGroup = {}
ArchaeologyDigSiteFrame = {}
Button = {}
CheckButton = {}
ColorSelect = {}
ControlPoint = {}
Cooldown = {}
DressUpModel = {}
EditBox = {}
Font = {}
FontInstance = {}
FontString = {}
---@class Frame
Frame = {}
GameTooltip = {}
LayeredRegion = {}
MessageFrame = {}
Minimap = {}
Model = {}
MovieFrame = {}
ParentedObject = {}
PlayerModel = {}
QuestPOIFrame = {}
Region = {}
Rotation = {}
Scale = {}
ScrollFrame = {}
ScrollingMessageFrame = {}
SimpleHTML = {}
Slider = {}

TabardModel = {}
Texture = {}
Translation = {}
UIObject = {}
VisibleRegion = {}


function Alpha:GetChange() end
function Alpha:GetDuration() end
function Alpha:GetElapsed() end
function Alpha:GetEndDelay() end
function Alpha:GetMaxFramerate() end
function Alpha:GetName() end
function Alpha:GetObjectType() end
function Alpha:GetOrder() end
function Alpha:GetParent() end
function Alpha:GetProgress() end
function Alpha:GetProgressWithDelay() end
function Alpha:GetRegionParent() end
function Alpha:GetSmoothProgress() end
function Alpha:GetSmoothing() end
function Alpha:GetStartDelay() end
function Alpha:IsDelaying() end
function Alpha:IsDone() end
function Alpha:IsPaused() end
function Alpha:IsPlaying() end
function Alpha:IsStopped() end
function Alpha:Pause() end
function Alpha:Play() end
function Alpha:SetSmoothProgress() end
function Alpha:Stop() end
function Animation:GetDuration() end
function Animation:GetElapsed() end
function Animation:GetEndDelay() end
function Animation:GetMaxFramerate() end
function Animation:GetName() end
function Animation:GetObjectType() end
function Animation:GetOrder() end
function Animation:GetParent() end
function Animation:GetProgress() end
function Animation:GetProgressWithDelay() end
function Animation:GetRegionParent() end
function Animation:GetSmoothProgress() end
function Animation:GetSmoothing() end
function Animation:GetStartDelay() end
function Animation:IsDelaying() end
function Animation:IsDone() end
function Animation:IsPaused() end
function Animation:IsPlaying() end
function Animation:IsStopped() end
function Animation:Pause() end
function Animation:Play() end
function Animation:SetSmoothProgress() end
function Animation:Stop() end
function AnimationGroup:Finish() end
function AnimationGroup:GetAnimations() end
function AnimationGroup:GetDuration() end
function AnimationGroup:GetInitialOffset() end
function AnimationGroup:GetLoopState() end
function AnimationGroup:GetLooping() end
function AnimationGroup:GetMaxOrder() end
function AnimationGroup:GetName() end
function AnimationGroup:GetObjectType() end
function AnimationGroup:GetParent() end
function AnimationGroup:GetProgress() end
function AnimationGroup:IsDone() end
function AnimationGroup:IsPaused() end
function AnimationGroup:IsPendingFinish() end
function AnimationGroup:IsPlaying() end
function AnimationGroup:Pause() end
function AnimationGroup:Play() end
function AnimationGroup:Stop() end
function ArchaeologyDigSiteFrame:AllowAttributeChanges() end
function ArchaeologyDigSiteFrame:CanChangeAttribute() end
function ArchaeologyDigSiteFrame:CanChangeProtectedState() end
function ArchaeologyDigSiteFrame:ClearAllPoints() end
function ArchaeologyDigSiteFrame:CreateTitleRegion() end
function ArchaeologyDigSiteFrame:DrawNone() end
function ArchaeologyDigSiteFrame:EnableMerging() end
function ArchaeologyDigSiteFrame:EnableSmoothing() end
function ArchaeologyDigSiteFrame:GetAlpha() end
function ArchaeologyDigSiteFrame:GetAnimationGroups() end
function ArchaeologyDigSiteFrame:GetBackdrop() end
function ArchaeologyDigSiteFrame:GetBackdropBorderColor() end
function ArchaeologyDigSiteFrame:GetBackdropColor() end
function ArchaeologyDigSiteFrame:GetBottom() end
function ArchaeologyDigSiteFrame:GetBoundsRect() end
function ArchaeologyDigSiteFrame:GetCenter() end
function ArchaeologyDigSiteFrame:GetChildren() end
function ArchaeologyDigSiteFrame:GetClampRectInsets() end
function ArchaeologyDigSiteFrame:GetDepth() end
function ArchaeologyDigSiteFrame:GetDontSavePosition() end
function ArchaeologyDigSiteFrame:GetEffectiveAlpha() end
function ArchaeologyDigSiteFrame:GetEffectiveDepth() end
function ArchaeologyDigSiteFrame:GetEffectiveScale() end
function ArchaeologyDigSiteFrame:GetFrameLevel() end
function ArchaeologyDigSiteFrame:GetFrameStrata() end
function ArchaeologyDigSiteFrame:GetHeight() end
function ArchaeologyDigSiteFrame:GetHitRectInsets() end
function ArchaeologyDigSiteFrame:GetID() end
function ArchaeologyDigSiteFrame:GetLeft() end
function ArchaeologyDigSiteFrame:GetMaxResize() end
function ArchaeologyDigSiteFrame:GetMinResize() end
function ArchaeologyDigSiteFrame:GetName() end
function ArchaeologyDigSiteFrame:GetNumChildren() end
function ArchaeologyDigSiteFrame:GetNumPoints() end
function ArchaeologyDigSiteFrame:GetNumRegions() end
function ArchaeologyDigSiteFrame:GetObjectType() end
function ArchaeologyDigSiteFrame:GetParent() end
function ArchaeologyDigSiteFrame:GetPropagateKeyboardInput() end
function ArchaeologyDigSiteFrame:GetRect() end
function ArchaeologyDigSiteFrame:GetRegions() end
function ArchaeologyDigSiteFrame:GetRight() end
function ArchaeologyDigSiteFrame:GetScale() end
function ArchaeologyDigSiteFrame:GetSize() end
function ArchaeologyDigSiteFrame:GetTitleRegion() end
function ArchaeologyDigSiteFrame:GetTop() end
function ArchaeologyDigSiteFrame:GetWidth() end
function ArchaeologyDigSiteFrame:Hide() end
function ArchaeologyDigSiteFrame:IsClampedToScreen() end
function ArchaeologyDigSiteFrame:IsDragging() end
function ArchaeologyDigSiteFrame:IsIgnoringDepth() end
function ArchaeologyDigSiteFrame:IsJoystickEnabled() end
function ArchaeologyDigSiteFrame:IsKeyboardEnabled() end
function ArchaeologyDigSiteFrame:IsMouseEnabled() end
function ArchaeologyDigSiteFrame:IsMouseWheelEnabled() end
function ArchaeologyDigSiteFrame:IsMovable() end
function ArchaeologyDigSiteFrame:IsProtected() end
function ArchaeologyDigSiteFrame:IsResizable() end
function ArchaeologyDigSiteFrame:IsShown() end
function ArchaeologyDigSiteFrame:IsToplevel() end
function ArchaeologyDigSiteFrame:IsUserPlaced() end
function ArchaeologyDigSiteFrame:IsVisible() end
function ArchaeologyDigSiteFrame:Lower() end
function ArchaeologyDigSiteFrame:Raise() end
function ArchaeologyDigSiteFrame:RegisterAllEvents() end
function ArchaeologyDigSiteFrame:SetBorderAlpha() end
function ArchaeologyDigSiteFrame:SetBorderScalar() end
function ArchaeologyDigSiteFrame:SetBorderTexture() end
function ArchaeologyDigSiteFrame:SetDontSavePosition() end
function ArchaeologyDigSiteFrame:SetFillAlpha() end
function ArchaeologyDigSiteFrame:SetFillTexture() end
function ArchaeologyDigSiteFrame:SetMergeThreshold() end
function ArchaeologyDigSiteFrame:SetPropagateKeyboardInput() end
function ArchaeologyDigSiteFrame:Show() end
function ArchaeologyDigSiteFrame:StartMoving() end
function ArchaeologyDigSiteFrame:StartSizing() end
function ArchaeologyDigSiteFrame:StopAnimating() end
function ArchaeologyDigSiteFrame:StopMovingOrSizing() end
function ArchaeologyDigSiteFrame:UnregisterAllEvents() end
function Button:AllowAttributeChanges() end
function Button:CanChangeAttribute() end
function Button:CanChangeProtectedState() end
function Button:ClearAllPoints() end
function Button:CreateTitleRegion() end
function Button:Disable() end
function Button:Enable() end
function Button:GetAlpha() end
function Button:GetAnimationGroups() end
function Button:GetBackdrop() end
function Button:GetBackdropBorderColor() end
function Button:GetBackdropColor() end
function Button:GetBottom() end
function Button:GetBoundsRect() end
function Button:GetButtonState() end
function Button:GetCenter() end
function Button:GetChildren() end
function Button:GetClampRectInsets() end
function Button:GetDepth() end
function Button:GetDisabledFontObject() end
function Button:GetDisabledTexture() end
function Button:GetDontSavePosition() end
function Button:GetEffectiveAlpha() end
function Button:GetEffectiveDepth() end
function Button:GetEffectiveScale() end
function Button:GetFontString() end
function Button:GetFrameLevel() end
function Button:GetFrameStrata() end
function Button:GetHeight() end
function Button:GetHighlightFontObject() end
function Button:GetHighlightTexture() end
function Button:GetHitRectInsets() end
function Button:GetID() end
function Button:GetLeft() end
function Button:GetMaxResize() end
function Button:GetMinResize() end
function Button:GetMotionScriptsWhileDisabled() end
function Button:GetName() end
function Button:GetNormalFontObject() end
function Button:GetNormalTexture() end
function Button:GetNumChildren() end
function Button:GetNumPoints() end
function Button:GetNumRegions() end
function Button:GetObjectType() end
function Button:GetParent() end
function Button:GetPropagateKeyboardInput() end
function Button:GetPushedTextOffset() end
function Button:GetPushedTexture() end
function Button:GetRect() end
function Button:GetRegions() end
function Button:GetRight() end
function Button:GetScale() end
function Button:GetSize() end
function Button:GetText() end
function Button:GetTextHeight() end
function Button:GetTextWidth() end
function Button:GetTitleRegion() end
function Button:GetTop() end
function Button:GetWidth() end
function Button:Hide() end
function Button:IsClampedToScreen() end
function Button:IsDragging() end
function Button:IsEnabled() end
function Button:IsIgnoringDepth() end
function Button:IsJoystickEnabled() end
function Button:IsKeyboardEnabled() end
function Button:IsMouseEnabled() end
function Button:IsMouseWheelEnabled() end
function Button:IsMovable() end
function Button:IsProtected() end
function Button:IsResizable() end
function Button:IsShown() end
function Button:IsToplevel() end
function Button:IsUserPlaced() end
function Button:IsVisible() end
function Button:LockHighlight() end
function Button:Lower() end
function Button:Raise() end
function Button:RegisterAllEvents() end
function Button:SetDontSavePosition() end
function Button:SetPropagateKeyboardInput() end
function Button:Show() end
function Button:StartMoving() end
function Button:StartSizing() end
function Button:StopAnimating() end
function Button:StopMovingOrSizing() end
function Button:UnlockHighlight() end
function Button:UnregisterAllEvents() end
function CheckButton:AllowAttributeChanges() end
function CheckButton:CanChangeAttribute() end
function CheckButton:CanChangeProtectedState() end
function CheckButton:ClearAllPoints() end
function CheckButton:CreateTitleRegion() end
function CheckButton:Disable() end
function CheckButton:Enable() end
function CheckButton:GetAlpha() end
function CheckButton:GetAnimationGroups() end
function CheckButton:GetBackdrop() end
function CheckButton:GetBackdropBorderColor() end
function CheckButton:GetBackdropColor() end
function CheckButton:GetBottom() end
function CheckButton:GetBoundsRect() end
function CheckButton:GetButtonState() end
function CheckButton:GetCenter() end
function CheckButton:GetChecked() end
function CheckButton:GetCheckedTexture() end
function CheckButton:GetChildren() end
function CheckButton:GetClampRectInsets() end
function CheckButton:GetDepth() end
function CheckButton:GetDisabledCheckedTexture() end
function CheckButton:GetDisabledFontObject() end
function CheckButton:GetDisabledTexture() end
function CheckButton:GetDontSavePosition() end
function CheckButton:GetEffectiveAlpha() end
function CheckButton:GetEffectiveDepth() end
function CheckButton:GetEffectiveScale() end
function CheckButton:GetFontString() end
function CheckButton:GetFrameLevel() end
function CheckButton:GetFrameStrata() end
function CheckButton:GetHeight() end
function CheckButton:GetHighlightFontObject() end
function CheckButton:GetHighlightTexture() end
function CheckButton:GetHitRectInsets() end
function CheckButton:GetID() end
function CheckButton:GetLeft() end
function CheckButton:GetMaxResize() end
function CheckButton:GetMinResize() end
function CheckButton:GetMotionScriptsWhileDisabled() end
function CheckButton:GetName() end
function CheckButton:GetNormalFontObject() end
function CheckButton:GetNormalTexture() end
function CheckButton:GetNumChildren() end
function CheckButton:GetNumPoints() end
function CheckButton:GetNumRegions() end
function CheckButton:GetObjectType() end
function CheckButton:GetParent() end
function CheckButton:GetPropagateKeyboardInput() end
function CheckButton:GetPushedTextOffset() end
function CheckButton:GetPushedTexture() end
function CheckButton:GetRect() end
function CheckButton:GetRegions() end
function CheckButton:GetRight() end
function CheckButton:GetScale() end
function CheckButton:GetSize() end
function CheckButton:GetText() end
function CheckButton:GetTextHeight() end
function CheckButton:GetTextWidth() end
function CheckButton:GetTitleRegion() end
function CheckButton:GetTop() end
function CheckButton:GetWidth() end
function CheckButton:Hide() end
function CheckButton:IsClampedToScreen() end
function CheckButton:IsDragging() end
function CheckButton:IsEnabled() end
function CheckButton:IsIgnoringDepth() end
function CheckButton:IsJoystickEnabled() end
function CheckButton:IsKeyboardEnabled() end
function CheckButton:IsMouseEnabled() end
function CheckButton:IsMouseWheelEnabled() end
function CheckButton:IsMovable() end
function CheckButton:IsProtected() end
function CheckButton:IsResizable() end
function CheckButton:IsShown() end
function CheckButton:IsToplevel() end
function CheckButton:IsUserPlaced() end
function CheckButton:IsVisible() end
function CheckButton:LockHighlight() end
function CheckButton:Lower() end
function CheckButton:Raise() end
function CheckButton:RegisterAllEvents() end
function CheckButton:SetDontSavePosition() end
function CheckButton:SetPropagateKeyboardInput() end
function CheckButton:Show() end
function CheckButton:StartMoving() end
function CheckButton:StartSizing() end
function CheckButton:StopAnimating() end
function CheckButton:StopMovingOrSizing() end
function CheckButton:UnlockHighlight() end
function CheckButton:UnregisterAllEvents() end
function ColorSelect:AllowAttributeChanges() end
function ColorSelect:CanChangeAttribute() end
function ColorSelect:CanChangeProtectedState() end
function ColorSelect:ClearAllPoints() end
function ColorSelect:CreateTitleRegion() end
function ColorSelect:GetAlpha() end
function ColorSelect:GetAnimationGroups() end
function ColorSelect:GetBackdrop() end
function ColorSelect:GetBackdropBorderColor() end
function ColorSelect:GetBackdropColor() end
function ColorSelect:GetBottom() end
function ColorSelect:GetBoundsRect() end
function ColorSelect:GetCenter() end
function ColorSelect:GetChildren() end
function ColorSelect:GetClampRectInsets() end
function ColorSelect:GetColorHSV() end
function ColorSelect:GetColorRGB() end
function ColorSelect:GetColorValueTexture() end
function ColorSelect:GetColorValueThumbTexture() end
function ColorSelect:GetColorWheelTexture() end
function ColorSelect:GetColorWheelThumbTexture() end
function ColorSelect:GetDepth() end
function ColorSelect:GetDontSavePosition() end
function ColorSelect:GetEffectiveAlpha() end
function ColorSelect:GetEffectiveDepth() end
function ColorSelect:GetEffectiveScale() end
function ColorSelect:GetFrameLevel() end
function ColorSelect:GetFrameStrata() end
function ColorSelect:GetHeight() end
function ColorSelect:GetHitRectInsets() end
function ColorSelect:GetID() end
function ColorSelect:GetLeft() end
function ColorSelect:GetMaxResize() end
function ColorSelect:GetMinResize() end
function ColorSelect:GetName() end
function ColorSelect:GetNumChildren() end
function ColorSelect:GetNumPoints() end
function ColorSelect:GetNumRegions() end
function ColorSelect:GetObjectType() end
function ColorSelect:GetParent() end
function ColorSelect:GetPropagateKeyboardInput() end
function ColorSelect:GetRect() end
function ColorSelect:GetRegions() end
function ColorSelect:GetRight() end
function ColorSelect:GetScale() end
function ColorSelect:GetSize() end
function ColorSelect:GetTitleRegion() end
function ColorSelect:GetTop() end
function ColorSelect:GetWidth() end
function ColorSelect:Hide() end
function ColorSelect:IsClampedToScreen() end
function ColorSelect:IsDragging() end
function ColorSelect:IsIgnoringDepth() end
function ColorSelect:IsJoystickEnabled() end
function ColorSelect:IsKeyboardEnabled() end
function ColorSelect:IsMouseEnabled() end
function ColorSelect:IsMouseWheelEnabled() end
function ColorSelect:IsMovable() end
function ColorSelect:IsProtected() end
function ColorSelect:IsResizable() end
function ColorSelect:IsShown() end
function ColorSelect:IsToplevel() end
function ColorSelect:IsUserPlaced() end
function ColorSelect:IsVisible() end
function ColorSelect:Lower() end
function ColorSelect:Raise() end
function ColorSelect:RegisterAllEvents() end
function ColorSelect:SetDontSavePosition() end
function ColorSelect:SetPropagateKeyboardInput() end
function ColorSelect:Show() end
function ColorSelect:StartMoving() end
function ColorSelect:StartSizing() end
function ColorSelect:StopAnimating() end
function ColorSelect:StopMovingOrSizing() end
function ColorSelect:UnregisterAllEvents() end
function ControlPoint:GetName() end
function ControlPoint:GetObjectType() end
function ControlPoint:GetOffset() end
function ControlPoint:GetOrder() end
function ControlPoint:GetParent() end
function Cooldown:AllowAttributeChanges() end
function Cooldown:CanChangeAttribute() end
function Cooldown:CanChangeProtectedState() end
function Cooldown:ClearAllPoints() end
function Cooldown:CreateTitleRegion() end
function Cooldown:GetAlpha() end
function Cooldown:GetAnimationGroups() end
function Cooldown:GetBackdrop() end
function Cooldown:GetBackdropBorderColor() end
function Cooldown:GetBackdropColor() end
function Cooldown:GetBottom() end
function Cooldown:GetBoundsRect() end
function Cooldown:GetCenter() end
function Cooldown:GetChildren() end
function Cooldown:GetClampRectInsets() end
function Cooldown:GetDepth() end
function Cooldown:GetDontSavePosition() end
function Cooldown:GetDrawEdge() end
function Cooldown:GetEffectiveAlpha() end
function Cooldown:GetEffectiveDepth() end
function Cooldown:GetEffectiveScale() end
function Cooldown:GetFrameLevel() end
function Cooldown:GetFrameStrata() end
function Cooldown:GetHeight() end
function Cooldown:GetHitRectInsets() end
function Cooldown:GetID() end
function Cooldown:GetLeft() end
function Cooldown:GetMaxResize() end
function Cooldown:GetMinResize() end
function Cooldown:GetName() end
function Cooldown:GetNumChildren() end
function Cooldown:GetNumPoints() end
function Cooldown:GetNumRegions() end
function Cooldown:GetObjectType() end
function Cooldown:GetParent() end
function Cooldown:GetPropagateKeyboardInput() end
function Cooldown:GetRect() end
function Cooldown:GetRegions() end
function Cooldown:GetReverse() end
function Cooldown:GetRight() end
function Cooldown:GetScale() end
function Cooldown:GetSize() end
function Cooldown:GetTitleRegion() end
function Cooldown:GetTop() end
function Cooldown:GetWidth() end
function Cooldown:Hide() end
function Cooldown:IsClampedToScreen() end
function Cooldown:IsDragging() end
function Cooldown:IsIgnoringDepth() end
function Cooldown:IsJoystickEnabled() end
function Cooldown:IsKeyboardEnabled() end
function Cooldown:IsMouseEnabled() end
function Cooldown:IsMouseWheelEnabled() end
function Cooldown:IsMovable() end
function Cooldown:IsProtected() end
function Cooldown:IsResizable() end
function Cooldown:IsShown() end
function Cooldown:IsToplevel() end
function Cooldown:IsUserPlaced() end
function Cooldown:IsVisible() end
function Cooldown:Lower() end
function Cooldown:Raise() end
function Cooldown:RegisterAllEvents() end
function Cooldown:SetDontSavePosition() end
function Cooldown:SetPropagateKeyboardInput() end
function Cooldown:Show() end
function Cooldown:StartMoving() end
function Cooldown:StartSizing() end
function Cooldown:StopAnimating() end
function Cooldown:StopMovingOrSizing() end
function Cooldown:UnregisterAllEvents() end
function DressUpModel:AdvanceTime() end
function DressUpModel:AllowAttributeChanges() end
function DressUpModel:CanChangeAttribute() end
function DressUpModel:CanChangeProtectedState() end
function DressUpModel:ClearAllPoints() end
function DressUpModel:ClearFog() end
function DressUpModel:ClearModel() end
function DressUpModel:CreateTitleRegion() end
function DressUpModel:Dress() end
function DressUpModel:GetAlpha() end
function DressUpModel:GetAnimationGroups() end
function DressUpModel:GetBackdrop() end
function DressUpModel:GetBackdropBorderColor() end
function DressUpModel:GetBackdropColor() end
function DressUpModel:GetBottom() end
function DressUpModel:GetBoundsRect() end
function DressUpModel:GetCenter() end
function DressUpModel:GetChildren() end
function DressUpModel:GetClampRectInsets() end
function DressUpModel:GetDepth() end
function DressUpModel:GetDontSavePosition() end
function DressUpModel:GetEffectiveAlpha() end
function DressUpModel:GetEffectiveDepth() end
function DressUpModel:GetEffectiveScale() end
function DressUpModel:GetFacing() end
function DressUpModel:GetFogColor() end
function DressUpModel:GetFogFar() end
function DressUpModel:GetFogNear() end
function DressUpModel:GetFrameLevel() end
function DressUpModel:GetFrameStrata() end
function DressUpModel:GetHeight() end
function DressUpModel:GetHitRectInsets() end
function DressUpModel:GetID() end
function DressUpModel:GetLeft() end
function DressUpModel:GetLight() end
function DressUpModel:GetMaxResize() end
function DressUpModel:GetMinResize() end
function DressUpModel:GetModel() end
function DressUpModel:GetModelScale() end
function DressUpModel:GetName() end
function DressUpModel:GetNumChildren() end
function DressUpModel:GetNumPoints() end
function DressUpModel:GetNumRegions() end
function DressUpModel:GetObjectType() end
function DressUpModel:GetParent() end
function DressUpModel:GetPosition() end
function DressUpModel:GetPropagateKeyboardInput() end
function DressUpModel:GetRect() end
function DressUpModel:GetRegions() end
function DressUpModel:GetRight() end
function DressUpModel:GetScale() end
function DressUpModel:GetSize() end
function DressUpModel:GetTitleRegion() end
function DressUpModel:GetTop() end
function DressUpModel:GetWidth() end
function DressUpModel:Hide() end
function DressUpModel:IsClampedToScreen() end
function DressUpModel:IsDragging() end
function DressUpModel:IsIgnoringDepth() end
function DressUpModel:IsJoystickEnabled() end
function DressUpModel:IsKeyboardEnabled() end
function DressUpModel:IsMouseEnabled() end
function DressUpModel:IsMouseWheelEnabled() end
function DressUpModel:IsMovable() end
function DressUpModel:IsProtected() end
function DressUpModel:IsResizable() end
function DressUpModel:IsShown() end
function DressUpModel:IsToplevel() end
function DressUpModel:IsUserPlaced() end
function DressUpModel:IsVisible() end
function DressUpModel:Lower() end
function DressUpModel:Raise() end
function DressUpModel:RefreshCamera() end
function DressUpModel:RefreshUnit() end
function DressUpModel:RegisterAllEvents() end
function DressUpModel:SetBarberShopAlternateForm() end
function DressUpModel:SetCamDistanceScale() end
function DressUpModel:SetDisplayInfo() end
function DressUpModel:SetDontSavePosition() end
function DressUpModel:SetPortraitZoom() end
function DressUpModel:SetPropagateKeyboardInput() end
function DressUpModel:Show() end
function DressUpModel:StartMoving() end
function DressUpModel:StartSizing() end
function DressUpModel:StopAnimating() end
function DressUpModel:StopMovingOrSizing() end
function DressUpModel:Undress() end
function DressUpModel:UnregisterAllEvents() end
function EditBox:AllowAttributeChanges() end
function EditBox:CanChangeAttribute() end
function EditBox:CanChangeProtectedState() end
function EditBox:ClearAllPoints() end
function EditBox:ClearFocus() end
function EditBox:ClearHistory() end
function EditBox:CreateTitleRegion() end
function EditBox:GetAlpha() end
function EditBox:GetAltArrowKeyMode() end
function EditBox:GetAnimationGroups() end
function EditBox:GetBackdrop() end
function EditBox:GetBackdropBorderColor() end
function EditBox:GetBackdropColor() end
function EditBox:GetBlinkSpeed() end
function EditBox:GetBottom() end
function EditBox:GetBoundsRect() end
function EditBox:GetCenter() end
function EditBox:GetChildren() end
function EditBox:GetClampRectInsets() end
function EditBox:GetCursorPosition() end
function EditBox:GetDepth() end
function EditBox:GetDontSavePosition() end
function EditBox:GetEffectiveAlpha() end
function EditBox:GetEffectiveDepth() end
function EditBox:GetEffectiveScale() end
function EditBox:GetFont() end
function EditBox:GetFontObject() end
function EditBox:GetFrameLevel() end
function EditBox:GetFrameStrata() end
function EditBox:GetHeight() end
function EditBox:GetHistoryLines() end
function EditBox:GetHitRectInsets() end
function EditBox:GetID() end
function EditBox:GetIndentedWordWrap() end
function EditBox:GetInputLanguage() end
function EditBox:GetJustifyH() end
function EditBox:GetJustifyV() end
function EditBox:GetLeft() end
function EditBox:GetMaxBytes() end
function EditBox:GetMaxLetters() end
function EditBox:GetMaxResize() end
function EditBox:GetMinResize() end
function EditBox:GetName() end
function EditBox:GetNumChildren() end
function EditBox:GetNumLetters() end
function EditBox:GetNumPoints() end
function EditBox:GetNumRegions() end
function EditBox:GetNumber() end
function EditBox:GetObjectType() end
function EditBox:GetParent() end
function EditBox:GetPropagateKeyboardInput() end
function EditBox:GetRect() end
function EditBox:GetRegions() end
function EditBox:GetRight() end
function EditBox:GetScale() end
function EditBox:GetShadowColor() end
function EditBox:GetShadowOffset() end
function EditBox:GetSize() end
function EditBox:GetSpacing() end
function EditBox:GetText() end
function EditBox:GetTextColor() end
function EditBox:GetTextInsets() end
function EditBox:GetTitleRegion() end
function EditBox:GetTop() end
function EditBox:GetUTF8CursorPosition() end
function EditBox:GetWidth() end
function EditBox:HasFocus() end
function EditBox:Hide() end
function EditBox:IsAutoFocus() end
function EditBox:IsClampedToScreen() end
function EditBox:IsCountInvisibleLetters() end
function EditBox:IsDragging() end
function EditBox:IsIgnoringDepth() end
function EditBox:IsInIMECompositionMode() end
function EditBox:IsJoystickEnabled() end
function EditBox:IsKeyboardEnabled() end
function EditBox:IsMouseEnabled() end
function EditBox:IsMouseWheelEnabled() end
function EditBox:IsMovable() end
function EditBox:IsMultiLine() end
function EditBox:IsNumeric() end
function EditBox:IsPassword() end
function EditBox:IsProtected() end
function EditBox:IsResizable() end
function EditBox:IsShown() end
function EditBox:IsToplevel() end
function EditBox:IsUserPlaced() end
function EditBox:IsVisible() end
function EditBox:Lower() end
function EditBox:Raise() end
function EditBox:RegisterAllEvents() end
function EditBox:SetCountInvisibleLetters() end
function EditBox:SetDontSavePosition() end
function EditBox:SetFocus() end
function EditBox:SetPropagateKeyboardInput() end
function EditBox:Show() end
function EditBox:StartMoving() end
function EditBox:StartSizing() end
function EditBox:StopAnimating() end
function EditBox:StopMovingOrSizing() end
function EditBox:ToggleInputLanguage() end
function EditBox:UnregisterAllEvents() end
function Font:GetAlpha() end
function Font:GetFont() end
function Font:GetFontObject() end
function Font:GetIndentedWordWrap() end
function Font:GetJustifyH() end
function Font:GetJustifyV() end
function Font:GetName() end
function Font:GetObjectType() end
function Font:GetShadowColor() end
function Font:GetShadowOffset() end
function Font:GetSpacing() end
function Font:GetTextColor() end
function Font:SetIndentedWordWrap() end
function FontInstance:GetFont() end
function FontInstance:GetFontObject() end
function FontInstance:GetJustifyH() end
function FontInstance:GetJustifyV() end
function FontInstance:GetName() end
function FontInstance:GetObjectType() end
function FontInstance:GetShadowColor() end
function FontInstance:GetShadowOffset() end
function FontInstance:GetSpacing() end
function FontInstance:GetTextColor() end
function FontString:CanChangeProtectedState() end
function FontString:CanNonSpaceWrap() end
function FontString:CanWordWrap() end
function FontString:ClearAllPoints() end
function FontString:GetAlpha() end
function FontString:GetAnimationGroups() end
function FontString:GetBottom() end
function FontString:GetCenter() end
function FontString:GetDrawLayer() end
function FontString:GetFieldSize() end
function FontString:GetFont() end
function FontString:GetFontObject() end
function FontString:GetHeight() end
function FontString:GetIndentedWordWrap() end
function FontString:GetJustifyH() end
function FontString:GetJustifyV() end
function FontString:GetLeft() end
function FontString:GetName() end
function FontString:GetNumPoints() end
function FontString:GetObjectType() end
function FontString:GetParent() end
function FontString:GetRect() end
function FontString:GetRight() end
function FontString:GetShadowColor() end
function FontString:GetShadowOffset() end
function FontString:GetSize() end
function FontString:GetSpacing() end
function FontString:GetStringHeight() end
function FontString:GetStringWidth() end
function FontString:GetText() end
function FontString:GetTextColor() end
function FontString:GetTop() end
function FontString:GetWidth() end
function FontString:GetWrappedWidth() end
function FontString:Hide() end
function FontString:IsDragging() end
function FontString:IsProtected() end
function FontString:IsShown() end
function FontString:IsTruncated() end
function FontString:IsVisible() end
function FontString:SetIndentedWordWrap() end
function FontString:Show() end
function FontString:StopAnimating() end
function Frame:AllowAttributeChanges() end
function Frame:CanChangeAttribute() end
function Frame:CanChangeProtectedState() end
function Frame:ClearAllPoints() end
function Frame:CreateTitleRegion() end
function Frame:GetAlpha() end
function Frame:GetAnimationGroups() end
function Frame:GetBackdrop() end
function Frame:GetBackdropBorderColor() end
function Frame:GetBackdropColor() end
function Frame:GetBottom() end
function Frame:GetBoundsRect() end
function Frame:GetCenter() end
function Frame:GetChildren() end
function Frame:GetClampRectInsets() end
function Frame:GetDepth() end
function Frame:GetDontSavePosition() end
function Frame:GetEffectiveAlpha() end
function Frame:GetEffectiveDepth() end
function Frame:GetEffectiveScale() end
function Frame:GetFrameLevel() end
function Frame:GetFrameStrata() end
function Frame:GetHeight() end
function Frame:GetHitRectInsets() end
function Frame:GetID() end
function Frame:GetLeft() end
function Frame:GetMaxResize() end
function Frame:GetMinResize() end
function Frame:GetName() end
function Frame:GetNumChildren() end
function Frame:GetNumPoints() end
function Frame:GetNumRegions() end
function Frame:GetObjectType() end
function Frame:GetParent() end
function Frame:GetPropagateKeyboardInput() end
function Frame:GetRect() end
function Frame:GetRegions() end
function Frame:GetRight() end
function Frame:GetScale() end
function Frame:GetSize() end
function Frame:GetTitleRegion() end
function Frame:GetTop() end
function Frame:GetWidth() end
function Frame:Hide() end
function Frame:IsClampedToScreen() end
function Frame:IsDragging() end
function Frame:IsIgnoringDepth() end
function Frame:IsJoystickEnabled() end
function Frame:IsKeyboardEnabled() end
function Frame:IsMouseEnabled() end
function Frame:IsMouseWheelEnabled() end
function Frame:IsMovable() end
function Frame:IsProtected() end
function Frame:IsResizable() end
function Frame:IsShown() end
function Frame:IsToplevel() end
function Frame:IsUserPlaced() end
function Frame:IsVisible() end
function Frame:Lower() end
function Frame:Raise() end
function Frame:RegisterAllEvents() end
function Frame:SetDontSavePosition() end
function Frame:SetPropagateKeyboardInput() end

---SetParent
---@param parent Frame string
function Frame:SetParent(parent) end

---SetPoint
---@param point string
---@param relativeTo Frame
---@param relativePoint string
---@param xOffset number
---@param yOffset number
function Frame:SetPoint(point, relativeTo, relativePoint, xOffset, yOffset) end

---@param func function
---@param type string
function Frame:SetScript(type, func) end

function Frame:Show() end
function Frame:StartMoving() end
function Frame:StartSizing() end
function Frame:StopAnimating() end
function Frame:StopMovingOrSizing() end
function Frame:UnregisterAllEvents() end
---@class GameTooltip
GameTooltip = {}
function GameTooltip:AddSpellByID() end
function GameTooltip:AllowAttributeChanges() end
function GameTooltip:CanChangeAttribute() end
function GameTooltip:CanChangeProtectedState() end
function GameTooltip:ClearAllPoints() end
function GameTooltip:ClearLines() end
function GameTooltip:CreateTitleRegion() end
function GameTooltip:FadeOut() end
function GameTooltip:GetAlpha() end
function GameTooltip:GetAnchorType() end
function GameTooltip:GetAnimationGroups() end
function GameTooltip:GetBackdrop() end
function GameTooltip:GetBackdropBorderColor() end
function GameTooltip:GetBackdropColor() end
function GameTooltip:GetBottom() end
function GameTooltip:GetBoundsRect() end
function GameTooltip:GetCenter() end
function GameTooltip:GetChildren() end
function GameTooltip:GetClampRectInsets() end
function GameTooltip:GetDepth() end
function GameTooltip:GetDontSavePosition() end
function GameTooltip:GetEffectiveAlpha() end
function GameTooltip:GetEffectiveDepth() end
function GameTooltip:GetEffectiveScale() end
function GameTooltip:GetFrameLevel() end
function GameTooltip:GetFrameStrata() end
function GameTooltip:GetHeight() end
function GameTooltip:GetHitRectInsets() end
function GameTooltip:GetID() end
function GameTooltip:GetItem() end
function GameTooltip:GetLeft() end
function GameTooltip:GetMaxResize() end
function GameTooltip:GetMinResize() end
function GameTooltip:GetMinimumWidth() end
function GameTooltip:GetName() end
function GameTooltip:GetNumChildren() end
function GameTooltip:GetNumPoints() end
function GameTooltip:GetNumRegions() end
function GameTooltip:GetObjectType() end
function GameTooltip:GetOwner() end
function GameTooltip:GetPadding() end
function GameTooltip:GetParent() end
function GameTooltip:GetPropagateKeyboardInput() end
function GameTooltip:GetRect() end
function GameTooltip:GetRegions() end
function GameTooltip:GetRight() end
function GameTooltip:GetScale() end
function GameTooltip:GetSize() end
function GameTooltip:GetSpell() end
function GameTooltip:GetTitleRegion() end
function GameTooltip:GetTop() end
function GameTooltip:GetUnit() end
function GameTooltip:GetWidth() end
function GameTooltip:Hide() end
function GameTooltip:IsClampedToScreen() end
function GameTooltip:IsDragging() end
function GameTooltip:IsEquippedItem() end
function GameTooltip:IsIgnoringDepth() end
function GameTooltip:IsJoystickEnabled() end
function GameTooltip:IsKeyboardEnabled() end
function GameTooltip:IsMouseEnabled() end
function GameTooltip:IsMouseWheelEnabled() end
function GameTooltip:IsMovable() end
function GameTooltip:IsOwned() end
function GameTooltip:IsProtected() end
function GameTooltip:IsResizable() end
function GameTooltip:IsShown() end
function GameTooltip:IsToplevel() end
function GameTooltip:IsUserPlaced() end
function GameTooltip:IsVisible() end
function GameTooltip:Lower() end
function GameTooltip:NumLines() end
function GameTooltip:Raise() end
function GameTooltip:RegisterAllEvents() end
function GameTooltip:SetAuctionSellItem() end
function GameTooltip:SetCurrencyByID() end
function GameTooltip:SetDontSavePosition() end
function GameTooltip:SetGlyphByID() end
function GameTooltip:SetInstanceLockEncountersComplete() end
function GameTooltip:SetInventoryItemByID() end
function GameTooltip:SetLFGCompletionReward() end
function GameTooltip:SetLFGDungeonReward() end
function GameTooltip:SetLootCurrency() end
function GameTooltip:SetPropagateKeyboardInput() end
function GameTooltip:SetQuestCurrency() end
function GameTooltip:SetQuestLogCurrency() end
function GameTooltip:SetQuestLogRewardSpell() end
function GameTooltip:SetQuestRewardSpell() end
function GameTooltip:SetReforgeItem() end
function GameTooltip:SetSocketedItem() end
function GameTooltip:SetSpellBookItem() end
function GameTooltip:Show() end
function GameTooltip:StartMoving() end
function GameTooltip:StartSizing() end
function GameTooltip:StopAnimating() end
function GameTooltip:StopMovingOrSizing() end
function GameTooltip:UnregisterAllEvents() end


function GameTooltip:SetOwner(frame, anchorType, xOffset, yOffset) end
function GameTooltip:AddLine(text, red, green, blue, wrapText) end

function LayeredRegion:CanChangeProtectedState() end
function LayeredRegion:ClearAllPoints() end
function LayeredRegion:GetAlpha() end
function LayeredRegion:GetAnimationGroups() end
function LayeredRegion:GetBottom() end
function LayeredRegion:GetCenter() end
function LayeredRegion:GetDrawLayer() end
function LayeredRegion:GetHeight() end
function LayeredRegion:GetLeft() end
function LayeredRegion:GetName() end
function LayeredRegion:GetNumPoints() end
function LayeredRegion:GetObjectType() end
function LayeredRegion:GetParent() end
function LayeredRegion:GetRect() end
function LayeredRegion:GetRight() end
function LayeredRegion:GetSize() end
function LayeredRegion:GetTop() end
function LayeredRegion:GetWidth() end
function LayeredRegion:Hide() end
function LayeredRegion:IsDragging() end
function LayeredRegion:IsProtected() end
function LayeredRegion:IsShown() end
function LayeredRegion:IsVisible() end
function LayeredRegion:Show() end
function LayeredRegion:StopAnimating() end
function MessageFrame:AllowAttributeChanges() end
function MessageFrame:CanChangeAttribute() end
function MessageFrame:CanChangeProtectedState() end
function MessageFrame:Clear() end
function MessageFrame:ClearAllPoints() end
function MessageFrame:CreateTitleRegion() end
function MessageFrame:GetAlpha() end
function MessageFrame:GetAnimationGroups() end
function MessageFrame:GetBackdrop() end
function MessageFrame:GetBackdropBorderColor() end
function MessageFrame:GetBackdropColor() end
function MessageFrame:GetBottom() end
function MessageFrame:GetBoundsRect() end
function MessageFrame:GetCenter() end
function MessageFrame:GetChildren() end
function MessageFrame:GetClampRectInsets() end
function MessageFrame:GetDepth() end
function MessageFrame:GetDontSavePosition() end
function MessageFrame:GetEffectiveAlpha() end
function MessageFrame:GetEffectiveDepth() end
function MessageFrame:GetEffectiveScale() end
function MessageFrame:GetFadeDuration() end
function MessageFrame:GetFading() end
function MessageFrame:GetFont() end
function MessageFrame:GetFontObject() end
function MessageFrame:GetFrameLevel() end
function MessageFrame:GetFrameStrata() end
function MessageFrame:GetHeight() end
function MessageFrame:GetHitRectInsets() end
function MessageFrame:GetID() end
function MessageFrame:GetIndentedWordWrap() end
function MessageFrame:GetInsertMode() end
function MessageFrame:GetJustifyH() end
function MessageFrame:GetJustifyV() end
function MessageFrame:GetLeft() end
function MessageFrame:GetMaxResize() end
function MessageFrame:GetMinResize() end
function MessageFrame:GetName() end
function MessageFrame:GetNumChildren() end
function MessageFrame:GetNumPoints() end
function MessageFrame:GetNumRegions() end
function MessageFrame:GetObjectType() end
function MessageFrame:GetParent() end
function MessageFrame:GetPropagateKeyboardInput() end
function MessageFrame:GetRect() end
function MessageFrame:GetRegions() end
function MessageFrame:GetRight() end
function MessageFrame:GetScale() end
function MessageFrame:GetShadowColor() end
function MessageFrame:GetShadowOffset() end
function MessageFrame:GetSize() end
function MessageFrame:GetSpacing() end
function MessageFrame:GetTextColor() end
function MessageFrame:GetTimeVisible() end
function MessageFrame:GetTitleRegion() end
function MessageFrame:GetTop() end
function MessageFrame:GetWidth() end
function MessageFrame:Hide() end
function MessageFrame:IsClampedToScreen() end
function MessageFrame:IsDragging() end
function MessageFrame:IsIgnoringDepth() end
function MessageFrame:IsJoystickEnabled() end
function MessageFrame:IsKeyboardEnabled() end
function MessageFrame:IsMouseEnabled() end
function MessageFrame:IsMouseWheelEnabled() end
function MessageFrame:IsMovable() end
function MessageFrame:IsProtected() end
function MessageFrame:IsResizable() end
function MessageFrame:IsShown() end
function MessageFrame:IsToplevel() end
function MessageFrame:IsUserPlaced() end
function MessageFrame:IsVisible() end
function MessageFrame:Lower() end
function MessageFrame:Raise() end
function MessageFrame:RegisterAllEvents() end
function MessageFrame:SetDontSavePosition() end
function MessageFrame:SetPropagateKeyboardInput() end
function MessageFrame:Show() end
function MessageFrame:StartMoving() end
function MessageFrame:StartSizing() end
function MessageFrame:StopAnimating() end
function MessageFrame:StopMovingOrSizing() end
function MessageFrame:UnregisterAllEvents() end
function Minimap:AllowAttributeChanges() end
function Minimap:CanChangeAttribute() end
function Minimap:CanChangeProtectedState() end
function Minimap:ClearAllPoints() end
function Minimap:CreateTitleRegion() end
function Minimap:GetAlpha() end
function Minimap:GetAnimationGroups() end
function Minimap:GetBackdrop() end
function Minimap:GetBackdropBorderColor() end
function Minimap:GetBackdropColor() end
function Minimap:GetBottom() end
function Minimap:GetBoundsRect() end
function Minimap:GetCenter() end
function Minimap:GetChildren() end
function Minimap:GetClampRectInsets() end
function Minimap:GetDepth() end
function Minimap:GetDontSavePosition() end
function Minimap:GetEffectiveAlpha() end
function Minimap:GetEffectiveDepth() end
function Minimap:GetEffectiveScale() end
function Minimap:GetFrameLevel() end
function Minimap:GetFrameStrata() end
function Minimap:GetHeight() end
function Minimap:GetHitRectInsets() end
function Minimap:GetID() end
function Minimap:GetLeft() end
function Minimap:GetMaxResize() end
function Minimap:GetMinResize() end
function Minimap:GetName() end
function Minimap:GetNumChildren() end
function Minimap:GetNumPoints() end
function Minimap:GetNumRegions() end
function Minimap:GetObjectType() end
function Minimap:GetParent() end
function Minimap:GetPingPosition() end
function Minimap:GetPropagateKeyboardInput() end
function Minimap:GetRect() end
function Minimap:GetRegions() end
function Minimap:GetRight() end
function Minimap:GetScale() end
function Minimap:GetSize() end
function Minimap:GetTitleRegion() end
function Minimap:GetTop() end
function Minimap:GetWidth() end
function Minimap:GetZoom() end
function Minimap:GetZoomLevels() end
function Minimap:Hide() end
function Minimap:IsClampedToScreen() end
function Minimap:IsDragging() end
function Minimap:IsIgnoringDepth() end
function Minimap:IsJoystickEnabled() end
function Minimap:IsKeyboardEnabled() end
function Minimap:IsMouseEnabled() end
function Minimap:IsMouseWheelEnabled() end
function Minimap:IsMovable() end
function Minimap:IsProtected() end
function Minimap:IsResizable() end
function Minimap:IsShown() end
function Minimap:IsToplevel() end
function Minimap:IsUserPlaced() end
function Minimap:IsVisible() end
function Minimap:Lower() end
function Minimap:Raise() end
function Minimap:RegisterAllEvents() end
function Minimap:SetDontSavePosition() end
function Minimap:SetPropagateKeyboardInput() end
function Minimap:Show() end
function Minimap:StartMoving() end
function Minimap:StartSizing() end
function Minimap:StopAnimating() end
function Minimap:StopMovingOrSizing() end
function Minimap:UnregisterAllEvents() end
function Model:AdvanceTime() end
function Model:AllowAttributeChanges() end
function Model:CanChangeAttribute() end
function Model:CanChangeProtectedState() end
function Model:ClearAllPoints() end
function Model:ClearFog() end
function Model:ClearModel() end
function Model:CreateTitleRegion() end
function Model:GetAlpha() end
function Model:GetAnimationGroups() end
function Model:GetBackdrop() end
function Model:GetBackdropBorderColor() end
function Model:GetBackdropColor() end
function Model:GetBottom() end
function Model:GetBoundsRect() end
function Model:GetCenter() end
function Model:GetChildren() end
function Model:GetClampRectInsets() end
function Model:GetDepth() end
function Model:GetDontSavePosition() end
function Model:GetEffectiveAlpha() end
function Model:GetEffectiveDepth() end
function Model:GetEffectiveScale() end
function Model:GetFacing() end
function Model:GetFogColor() end
function Model:GetFogFar() end
function Model:GetFogNear() end
function Model:GetFrameLevel() end
function Model:GetFrameStrata() end
function Model:GetHeight() end
function Model:GetHitRectInsets() end
function Model:GetID() end
function Model:GetLeft() end
function Model:GetLight() end
function Model:GetMaxResize() end
function Model:GetMinResize() end
function Model:GetModel() end
function Model:GetModelScale() end
function Model:GetName() end
function Model:GetNumChildren() end
function Model:GetNumPoints() end
function Model:GetNumRegions() end
function Model:GetObjectType() end
function Model:GetParent() end
function Model:GetPosition() end
function Model:GetPropagateKeyboardInput() end
function Model:GetRect() end
function Model:GetRegions() end
function Model:GetRight() end
function Model:GetScale() end
function Model:GetSize() end
function Model:GetTitleRegion() end
function Model:GetTop() end
function Model:GetWidth() end
function Model:Hide() end
function Model:IsClampedToScreen() end
function Model:IsDragging() end
function Model:IsIgnoringDepth() end
function Model:IsJoystickEnabled() end
function Model:IsKeyboardEnabled() end
function Model:IsMouseEnabled() end
function Model:IsMouseWheelEnabled() end
function Model:IsMovable() end
function Model:IsProtected() end
function Model:IsResizable() end
function Model:IsShown() end
function Model:IsToplevel() end
function Model:IsUserPlaced() end
function Model:IsVisible() end
function Model:Lower() end
function Model:Raise() end
function Model:RegisterAllEvents() end
function Model:SetDontSavePosition() end
function Model:SetPropagateKeyboardInput() end
function Model:Show() end
function Model:StartMoving() end
function Model:StartSizing() end
function Model:StopAnimating() end
function Model:StopMovingOrSizing() end
function Model:UnregisterAllEvents() end
function MovieFrame:AllowAttributeChanges() end
function MovieFrame:CanChangeAttribute() end
function MovieFrame:CanChangeProtectedState() end
function MovieFrame:ClearAllPoints() end
function MovieFrame:CreateTitleRegion() end
function MovieFrame:GetAlpha() end
function MovieFrame:GetAnimationGroups() end
function MovieFrame:GetBackdrop() end
function MovieFrame:GetBackdropBorderColor() end
function MovieFrame:GetBackdropColor() end
function MovieFrame:GetBottom() end
function MovieFrame:GetBoundsRect() end
function MovieFrame:GetCenter() end
function MovieFrame:GetChildren() end
function MovieFrame:GetClampRectInsets() end
function MovieFrame:GetDepth() end
function MovieFrame:GetDontSavePosition() end
function MovieFrame:GetEffectiveAlpha() end
function MovieFrame:GetEffectiveDepth() end
function MovieFrame:GetEffectiveScale() end
function MovieFrame:GetFrameLevel() end
function MovieFrame:GetFrameStrata() end
function MovieFrame:GetHeight() end
function MovieFrame:GetHitRectInsets() end
function MovieFrame:GetID() end
function MovieFrame:GetLeft() end
function MovieFrame:GetMaxResize() end
function MovieFrame:GetMinResize() end
function MovieFrame:GetName() end
function MovieFrame:GetNumChildren() end
function MovieFrame:GetNumPoints() end
function MovieFrame:GetNumRegions() end
function MovieFrame:GetObjectType() end
function MovieFrame:GetParent() end
function MovieFrame:GetPropagateKeyboardInput() end
function MovieFrame:GetRect() end
function MovieFrame:GetRegions() end
function MovieFrame:GetRight() end
function MovieFrame:GetScale() end
function MovieFrame:GetSize() end
function MovieFrame:GetTitleRegion() end
function MovieFrame:GetTop() end
function MovieFrame:GetWidth() end
function MovieFrame:Hide() end
function MovieFrame:IsClampedToScreen() end
function MovieFrame:IsDragging() end
function MovieFrame:IsIgnoringDepth() end
function MovieFrame:IsJoystickEnabled() end
function MovieFrame:IsKeyboardEnabled() end
function MovieFrame:IsMouseEnabled() end
function MovieFrame:IsMouseWheelEnabled() end
function MovieFrame:IsMovable() end
function MovieFrame:IsProtected() end
function MovieFrame:IsResizable() end
function MovieFrame:IsShown() end
function MovieFrame:IsToplevel() end
function MovieFrame:IsUserPlaced() end
function MovieFrame:IsVisible() end
function MovieFrame:Lower() end
function MovieFrame:Raise() end
function MovieFrame:RegisterAllEvents() end
function MovieFrame:SetDontSavePosition() end
function MovieFrame:SetPropagateKeyboardInput() end
function MovieFrame:Show() end
function MovieFrame:StartMoving() end
function MovieFrame:StartSizing() end
function MovieFrame:StopAnimating() end
function MovieFrame:StopMovie() end
function MovieFrame:StopMovingOrSizing() end
function MovieFrame:UnregisterAllEvents() end
function ParentedObject:GetName() end
function ParentedObject:GetObjectType() end
function ParentedObject:GetParent() end
function PlayerModel:AdvanceTime() end
function PlayerModel:AllowAttributeChanges() end
function PlayerModel:CanChangeAttribute() end
function PlayerModel:CanChangeProtectedState() end
function PlayerModel:ClearAllPoints() end
function PlayerModel:ClearFog() end
function PlayerModel:ClearModel() end
function PlayerModel:CreateTitleRegion() end
function PlayerModel:GetAlpha() end
function PlayerModel:GetAnimationGroups() end
function PlayerModel:GetBackdrop() end
function PlayerModel:GetBackdropBorderColor() end
function PlayerModel:GetBackdropColor() end
function PlayerModel:GetBottom() end
function PlayerModel:GetBoundsRect() end
function PlayerModel:GetCenter() end
function PlayerModel:GetChildren() end
function PlayerModel:GetClampRectInsets() end
function PlayerModel:GetDepth() end
function PlayerModel:GetDontSavePosition() end
function PlayerModel:GetEffectiveAlpha() end
function PlayerModel:GetEffectiveDepth() end
function PlayerModel:GetEffectiveScale() end
function PlayerModel:GetFacing() end
function PlayerModel:GetFogColor() end
function PlayerModel:GetFogFar() end
function PlayerModel:GetFogNear() end
function PlayerModel:GetFrameLevel() end
function PlayerModel:GetFrameStrata() end
function PlayerModel:GetHeight() end
function PlayerModel:GetHitRectInsets() end
function PlayerModel:GetID() end
function PlayerModel:GetLeft() end
function PlayerModel:GetLight() end
function PlayerModel:GetMaxResize() end
function PlayerModel:GetMinResize() end
function PlayerModel:GetModel() end
function PlayerModel:GetModelScale() end
function PlayerModel:GetName() end
function PlayerModel:GetNumChildren() end
function PlayerModel:GetNumPoints() end
function PlayerModel:GetNumRegions() end
function PlayerModel:GetObjectType() end
function PlayerModel:GetParent() end
function PlayerModel:GetPosition() end
function PlayerModel:GetPropagateKeyboardInput() end
function PlayerModel:GetRect() end
function PlayerModel:GetRegions() end
function PlayerModel:GetRight() end
function PlayerModel:GetScale() end
function PlayerModel:GetSize() end
function PlayerModel:GetTitleRegion() end
function PlayerModel:GetTop() end
function PlayerModel:GetWidth() end
function PlayerModel:Hide() end
function PlayerModel:IsClampedToScreen() end
function PlayerModel:IsDragging() end
function PlayerModel:IsIgnoringDepth() end
function PlayerModel:IsJoystickEnabled() end
function PlayerModel:IsKeyboardEnabled() end
function PlayerModel:IsMouseEnabled() end
function PlayerModel:IsMouseWheelEnabled() end
function PlayerModel:IsMovable() end
function PlayerModel:IsProtected() end
function PlayerModel:IsResizable() end
function PlayerModel:IsShown() end
function PlayerModel:IsToplevel() end
function PlayerModel:IsUserPlaced() end
function PlayerModel:IsVisible() end
function PlayerModel:Lower() end
function PlayerModel:Raise() end
function PlayerModel:RefreshCamera() end
function PlayerModel:RefreshUnit() end
function PlayerModel:RegisterAllEvents() end
function PlayerModel:SetBarberShopAlternateForm() end
function PlayerModel:SetCamDistanceScale() end
function PlayerModel:SetDisplayInfo() end
function PlayerModel:SetDontSavePosition() end
function PlayerModel:SetPortraitZoom() end
function PlayerModel:SetPropagateKeyboardInput() end
function PlayerModel:Show() end
function PlayerModel:StartMoving() end
function PlayerModel:StartSizing() end
function PlayerModel:StopAnimating() end
function PlayerModel:StopMovingOrSizing() end
function PlayerModel:UnregisterAllEvents() end
function QuestPOIFrame:AllowAttributeChanges() end
function QuestPOIFrame:CanChangeAttribute() end
function QuestPOIFrame:CanChangeProtectedState() end
function QuestPOIFrame:ClearAllPoints() end
function QuestPOIFrame:CreateTitleRegion() end
function QuestPOIFrame:DrawNone() end
function QuestPOIFrame:EnableMerging() end
function QuestPOIFrame:EnableSmoothing() end
function QuestPOIFrame:GetAlpha() end
function QuestPOIFrame:GetAnimationGroups() end
function QuestPOIFrame:GetBackdrop() end
function QuestPOIFrame:GetBackdropBorderColor() end
function QuestPOIFrame:GetBackdropColor() end
function QuestPOIFrame:GetBottom() end
function QuestPOIFrame:GetBoundsRect() end
function QuestPOIFrame:GetCenter() end
function QuestPOIFrame:GetChildren() end
function QuestPOIFrame:GetClampRectInsets() end
function QuestPOIFrame:GetDepth() end
function QuestPOIFrame:GetDontSavePosition() end
function QuestPOIFrame:GetEffectiveAlpha() end
function QuestPOIFrame:GetEffectiveDepth() end
function QuestPOIFrame:GetEffectiveScale() end
function QuestPOIFrame:GetFrameLevel() end
function QuestPOIFrame:GetFrameStrata() end
function QuestPOIFrame:GetHeight() end
function QuestPOIFrame:GetHitRectInsets() end
function QuestPOIFrame:GetID() end
function QuestPOIFrame:GetLeft() end
function QuestPOIFrame:GetMaxResize() end
function QuestPOIFrame:GetMinResize() end
function QuestPOIFrame:GetName() end
function QuestPOIFrame:GetNumChildren() end
function QuestPOIFrame:GetNumPoints() end
function QuestPOIFrame:GetNumRegions() end
function QuestPOIFrame:GetNumTooltips() end
function QuestPOIFrame:GetObjectType() end
function QuestPOIFrame:GetParent() end
function QuestPOIFrame:GetPropagateKeyboardInput() end
function QuestPOIFrame:GetRect() end
function QuestPOIFrame:GetRegions() end
function QuestPOIFrame:GetRight() end
function QuestPOIFrame:GetScale() end
function QuestPOIFrame:GetSize() end
function QuestPOIFrame:GetTitleRegion() end
function QuestPOIFrame:GetTooltipIndex() end
function QuestPOIFrame:GetTop() end
function QuestPOIFrame:GetWidth() end
function QuestPOIFrame:Hide() end
function QuestPOIFrame:IsClampedToScreen() end
function QuestPOIFrame:IsDragging() end
function QuestPOIFrame:IsIgnoringDepth() end
function QuestPOIFrame:IsJoystickEnabled() end
function QuestPOIFrame:IsKeyboardEnabled() end
function QuestPOIFrame:IsMouseEnabled() end
function QuestPOIFrame:IsMouseWheelEnabled() end
function QuestPOIFrame:IsMovable() end
function QuestPOIFrame:IsProtected() end
function QuestPOIFrame:IsResizable() end
function QuestPOIFrame:IsShown() end
function QuestPOIFrame:IsToplevel() end
function QuestPOIFrame:IsUserPlaced() end
function QuestPOIFrame:IsVisible() end
function QuestPOIFrame:Lower() end
function QuestPOIFrame:Raise() end
function QuestPOIFrame:RegisterAllEvents() end
function QuestPOIFrame:SetDontSavePosition() end
function QuestPOIFrame:SetMergeThreshold() end
function QuestPOIFrame:SetNumSplinePoints() end
function QuestPOIFrame:SetPropagateKeyboardInput() end
function QuestPOIFrame:Show() end
function QuestPOIFrame:StartMoving() end
function QuestPOIFrame:StartSizing() end
function QuestPOIFrame:StopAnimating() end
function QuestPOIFrame:StopMovingOrSizing() end
function QuestPOIFrame:UnregisterAllEvents() end
function QuestPOIFrame:UpdateMouseOverTooltip() end
function Region:CanChangeProtectedState() end
function Region:ClearAllPoints() end
function Region:GetAnimationGroups() end
function Region:GetBottom() end
function Region:GetCenter() end
function Region:GetHeight() end
function Region:GetLeft() end
function Region:GetName() end
function Region:GetNumPoints() end
function Region:GetObjectType() end
function Region:GetParent() end
function Region:GetRect() end
function Region:GetRight() end
function Region:GetSize() end
function Region:GetTop() end
function Region:GetWidth() end
function Region:IsDragging() end
function Region:IsProtected() end
function Region:StopAnimating() end
function Rotation:GetDegrees() end
function Rotation:GetDuration() end
function Rotation:GetElapsed() end
function Rotation:GetEndDelay() end
function Rotation:GetMaxFramerate() end
function Rotation:GetName() end
function Rotation:GetObjectType() end
function Rotation:GetOrder() end
function Rotation:GetOrigin() end
function Rotation:GetParent() end
function Rotation:GetProgress() end
function Rotation:GetProgressWithDelay() end
function Rotation:GetRadians() end
function Rotation:GetRegionParent() end
function Rotation:GetSmoothProgress() end
function Rotation:GetSmoothing() end
function Rotation:GetStartDelay() end
function Rotation:IsDelaying() end
function Rotation:IsDone() end
function Rotation:IsPaused() end
function Rotation:IsPlaying() end
function Rotation:IsStopped() end
function Rotation:Pause() end
function Rotation:Play() end
function Rotation:SetSmoothProgress() end
function Rotation:Stop() end
function Scale:GetDuration() end
function Scale:GetElapsed() end
function Scale:GetEndDelay() end
function Scale:GetMaxFramerate() end
function Scale:GetName() end
function Scale:GetObjectType() end
function Scale:GetOrder() end
function Scale:GetOrigin() end
function Scale:GetParent() end
function Scale:GetProgress() end
function Scale:GetProgressWithDelay() end
function Scale:GetRegionParent() end
function Scale:GetScale() end
function Scale:GetSmoothProgress() end
function Scale:GetSmoothing() end
function Scale:GetStartDelay() end
function Scale:IsDelaying() end
function Scale:IsDone() end
function Scale:IsPaused() end
function Scale:IsPlaying() end
function Scale:IsStopped() end
function Scale:Pause() end
function Scale:Play() end
function Scale:SetSmoothProgress() end
function Scale:Stop() end
function ScrollFrame:AllowAttributeChanges() end
function ScrollFrame:CanChangeAttribute() end
function ScrollFrame:CanChangeProtectedState() end
function ScrollFrame:ClearAllPoints() end
function ScrollFrame:CreateTitleRegion() end
function ScrollFrame:GetAlpha() end
function ScrollFrame:GetAnimationGroups() end
function ScrollFrame:GetBackdrop() end
function ScrollFrame:GetBackdropBorderColor() end
function ScrollFrame:GetBackdropColor() end
function ScrollFrame:GetBottom() end
function ScrollFrame:GetBoundsRect() end
function ScrollFrame:GetCenter() end
function ScrollFrame:GetChildren() end
function ScrollFrame:GetClampRectInsets() end
function ScrollFrame:GetDepth() end
function ScrollFrame:GetDontSavePosition() end
function ScrollFrame:GetEffectiveAlpha() end
function ScrollFrame:GetEffectiveDepth() end
function ScrollFrame:GetEffectiveScale() end
function ScrollFrame:GetFrameLevel() end
function ScrollFrame:GetFrameStrata() end
function ScrollFrame:GetHeight() end
function ScrollFrame:GetHitRectInsets() end
function ScrollFrame:GetHorizontalScroll() end
function ScrollFrame:GetHorizontalScrollRange() end
function ScrollFrame:GetID() end
function ScrollFrame:GetLeft() end
function ScrollFrame:GetMaxResize() end
function ScrollFrame:GetMinResize() end
function ScrollFrame:GetName() end
function ScrollFrame:GetNumChildren() end
function ScrollFrame:GetNumPoints() end
function ScrollFrame:GetNumRegions() end
function ScrollFrame:GetObjectType() end
function ScrollFrame:GetParent() end
function ScrollFrame:GetPropagateKeyboardInput() end
function ScrollFrame:GetRect() end
function ScrollFrame:GetRegions() end
function ScrollFrame:GetRight() end
function ScrollFrame:GetScale() end
function ScrollFrame:GetScrollChild() end
function ScrollFrame:GetSize() end
function ScrollFrame:GetTitleRegion() end
function ScrollFrame:GetTop() end
function ScrollFrame:GetVerticalScroll() end
function ScrollFrame:GetVerticalScrollRange() end
function ScrollFrame:GetWidth() end
function ScrollFrame:Hide() end
function ScrollFrame:IsClampedToScreen() end
function ScrollFrame:IsDragging() end
function ScrollFrame:IsIgnoringDepth() end
function ScrollFrame:IsJoystickEnabled() end
function ScrollFrame:IsKeyboardEnabled() end
function ScrollFrame:IsMouseEnabled() end
function ScrollFrame:IsMouseWheelEnabled() end
function ScrollFrame:IsMovable() end
function ScrollFrame:IsProtected() end
function ScrollFrame:IsResizable() end
function ScrollFrame:IsShown() end
function ScrollFrame:IsToplevel() end
function ScrollFrame:IsUserPlaced() end
function ScrollFrame:IsVisible() end
function ScrollFrame:Lower() end
function ScrollFrame:Raise() end
function ScrollFrame:RegisterAllEvents() end
function ScrollFrame:SetDontSavePosition() end
function ScrollFrame:SetPropagateKeyboardInput() end
function ScrollFrame:Show() end
function ScrollFrame:StartMoving() end
function ScrollFrame:StartSizing() end
function ScrollFrame:StopAnimating() end
function ScrollFrame:StopMovingOrSizing() end
function ScrollFrame:UnregisterAllEvents() end
function ScrollFrame:UpdateScrollChildRect() end
function ScrollingMessageFrame:AllowAttributeChanges() end
function ScrollingMessageFrame:AtBottom() end
function ScrollingMessageFrame:AtTop() end
function ScrollingMessageFrame:CanChangeAttribute() end
function ScrollingMessageFrame:CanChangeProtectedState() end
function ScrollingMessageFrame:Clear() end
function ScrollingMessageFrame:ClearAllPoints() end
function ScrollingMessageFrame:CreateTitleRegion() end
function ScrollingMessageFrame:GetAlpha() end
function ScrollingMessageFrame:GetAnimationGroups() end
function ScrollingMessageFrame:GetBackdrop() end
function ScrollingMessageFrame:GetBackdropBorderColor() end
function ScrollingMessageFrame:GetBackdropColor() end
function ScrollingMessageFrame:GetBottom() end
function ScrollingMessageFrame:GetBoundsRect() end
function ScrollingMessageFrame:GetCenter() end
function ScrollingMessageFrame:GetChildren() end
function ScrollingMessageFrame:GetClampRectInsets() end
function ScrollingMessageFrame:GetCurrentLine() end
function ScrollingMessageFrame:GetCurrentScroll() end
function ScrollingMessageFrame:GetDepth() end
function ScrollingMessageFrame:GetDontSavePosition() end
function ScrollingMessageFrame:GetEffectiveAlpha() end
function ScrollingMessageFrame:GetEffectiveDepth() end
function ScrollingMessageFrame:GetEffectiveScale() end
function ScrollingMessageFrame:GetFadeDuration() end
function ScrollingMessageFrame:GetFading() end
function ScrollingMessageFrame:GetFont() end
function ScrollingMessageFrame:GetFontObject() end
function ScrollingMessageFrame:GetFrameLevel() end
function ScrollingMessageFrame:GetFrameStrata() end
function ScrollingMessageFrame:GetHeight() end
function ScrollingMessageFrame:GetHitRectInsets() end
function ScrollingMessageFrame:GetHyperlinksEnabled() end
function ScrollingMessageFrame:GetID() end
function ScrollingMessageFrame:GetIndentedWordWrap() end
function ScrollingMessageFrame:GetInsertMode() end
function ScrollingMessageFrame:GetJustifyH() end
function ScrollingMessageFrame:GetJustifyV() end
function ScrollingMessageFrame:GetLeft() end
function ScrollingMessageFrame:GetMaxResize() end
function ScrollingMessageFrame:GetMessageInfo() end
function ScrollingMessageFrame:GetMinResize() end
function ScrollingMessageFrame:GetName() end
function ScrollingMessageFrame:GetNumChildren() end
function ScrollingMessageFrame:GetNumLinesDisplayed() end
function ScrollingMessageFrame:GetNumMessages() end
function ScrollingMessageFrame:GetNumPoints() end
function ScrollingMessageFrame:GetNumRegions() end
function ScrollingMessageFrame:GetObjectType() end
function ScrollingMessageFrame:GetParent() end
function ScrollingMessageFrame:GetPropagateKeyboardInput() end
function ScrollingMessageFrame:GetRect() end
function ScrollingMessageFrame:GetRegions() end
function ScrollingMessageFrame:GetRight() end
function ScrollingMessageFrame:GetScale() end
function ScrollingMessageFrame:GetShadowColor() end
function ScrollingMessageFrame:GetShadowOffset() end
function ScrollingMessageFrame:GetSize() end
function ScrollingMessageFrame:GetSpacing() end
function ScrollingMessageFrame:GetTextColor() end
function ScrollingMessageFrame:GetTimeVisible() end
function ScrollingMessageFrame:GetTitleRegion() end
function ScrollingMessageFrame:GetTop() end
function ScrollingMessageFrame:GetWidth() end
function ScrollingMessageFrame:Hide() end
function ScrollingMessageFrame:IsClampedToScreen() end
function ScrollingMessageFrame:IsDragging() end
function ScrollingMessageFrame:IsIgnoringDepth() end
function ScrollingMessageFrame:IsJoystickEnabled() end
function ScrollingMessageFrame:IsKeyboardEnabled() end
function ScrollingMessageFrame:IsMouseEnabled() end
function ScrollingMessageFrame:IsMouseWheelEnabled() end
function ScrollingMessageFrame:IsMovable() end
function ScrollingMessageFrame:IsProtected() end
function ScrollingMessageFrame:IsResizable() end
function ScrollingMessageFrame:IsShown() end
function ScrollingMessageFrame:IsToplevel() end
function ScrollingMessageFrame:IsUserPlaced() end
function ScrollingMessageFrame:IsVisible() end
function ScrollingMessageFrame:Lower() end
function ScrollingMessageFrame:PageDown() end
function ScrollingMessageFrame:PageUp() end
function ScrollingMessageFrame:Raise() end
function ScrollingMessageFrame:RegisterAllEvents() end
function ScrollingMessageFrame:RemoveMessagesByAccessID() end
function ScrollingMessageFrame:ScrollDown() end
function ScrollingMessageFrame:ScrollToBottom() end
function ScrollingMessageFrame:ScrollToTop() end
function ScrollingMessageFrame:ScrollUp() end
function ScrollingMessageFrame:SetDontSavePosition() end
function ScrollingMessageFrame:SetPropagateKeyboardInput() end
function ScrollingMessageFrame:Show() end
function ScrollingMessageFrame:StartMoving() end
function ScrollingMessageFrame:StartSizing() end
function ScrollingMessageFrame:StopAnimating() end
function ScrollingMessageFrame:StopMovingOrSizing() end
function ScrollingMessageFrame:UnregisterAllEvents() end
function SimpleHTML:AllowAttributeChanges() end
function SimpleHTML:CanChangeAttribute() end
function SimpleHTML:CanChangeProtectedState() end
function SimpleHTML:ClearAllPoints() end
function SimpleHTML:CreateTitleRegion() end
function SimpleHTML:GetAlpha() end
function SimpleHTML:GetAnimationGroups() end
function SimpleHTML:GetBackdrop() end
function SimpleHTML:GetBackdropBorderColor() end
function SimpleHTML:GetBackdropColor() end
function SimpleHTML:GetBottom() end
function SimpleHTML:GetBoundsRect() end
function SimpleHTML:GetCenter() end
function SimpleHTML:GetChildren() end
function SimpleHTML:GetClampRectInsets() end
function SimpleHTML:GetDepth() end
function SimpleHTML:GetDontSavePosition() end
function SimpleHTML:GetEffectiveAlpha() end
function SimpleHTML:GetEffectiveDepth() end
function SimpleHTML:GetEffectiveScale() end
function SimpleHTML:GetFrameLevel() end
function SimpleHTML:GetFrameStrata() end
function SimpleHTML:GetHeight() end
function SimpleHTML:GetHitRectInsets() end
function SimpleHTML:GetHyperlinkFormat() end
function SimpleHTML:GetHyperlinksEnabled() end
function SimpleHTML:GetID() end
function SimpleHTML:GetLeft() end
function SimpleHTML:GetMaxResize() end
function SimpleHTML:GetMinResize() end
function SimpleHTML:GetName() end
function SimpleHTML:GetNumChildren() end
function SimpleHTML:GetNumPoints() end
function SimpleHTML:GetNumRegions() end
function SimpleHTML:GetObjectType() end
function SimpleHTML:GetParent() end
function SimpleHTML:GetPropagateKeyboardInput() end
function SimpleHTML:GetRect() end
function SimpleHTML:GetRegions() end
function SimpleHTML:GetRight() end
function SimpleHTML:GetScale() end
function SimpleHTML:GetSize() end
function SimpleHTML:GetTitleRegion() end
function SimpleHTML:GetTop() end
function SimpleHTML:GetWidth() end
function SimpleHTML:Hide() end
function SimpleHTML:IsClampedToScreen() end
function SimpleHTML:IsDragging() end
function SimpleHTML:IsIgnoringDepth() end
function SimpleHTML:IsJoystickEnabled() end
function SimpleHTML:IsKeyboardEnabled() end
function SimpleHTML:IsMouseEnabled() end
function SimpleHTML:IsMouseWheelEnabled() end
function SimpleHTML:IsMovable() end
function SimpleHTML:IsProtected() end
function SimpleHTML:IsResizable() end
function SimpleHTML:IsShown() end
function SimpleHTML:IsToplevel() end
function SimpleHTML:IsUserPlaced() end
function SimpleHTML:IsVisible() end
function SimpleHTML:Lower() end
function SimpleHTML:Raise() end
function SimpleHTML:RegisterAllEvents() end
function SimpleHTML:SetDontSavePosition() end
function SimpleHTML:SetPropagateKeyboardInput() end
function SimpleHTML:Show() end
function SimpleHTML:StartMoving() end
function SimpleHTML:StartSizing() end
function SimpleHTML:StopAnimating() end
function SimpleHTML:StopMovingOrSizing() end
function SimpleHTML:UnregisterAllEvents() end
function Slider:AllowAttributeChanges() end
function Slider:CanChangeAttribute() end
function Slider:CanChangeProtectedState() end
function Slider:ClearAllPoints() end
function Slider:CreateTitleRegion() end
function Slider:Disable() end
function Slider:Enable() end
function Slider:GetAlpha() end
function Slider:GetAnimationGroups() end
function Slider:GetBackdrop() end
function Slider:GetBackdropBorderColor() end
function Slider:GetBackdropColor() end
function Slider:GetBottom() end
function Slider:GetBoundsRect() end
function Slider:GetCenter() end
function Slider:GetChildren() end
function Slider:GetClampRectInsets() end
function Slider:GetDepth() end
function Slider:GetDontSavePosition() end
function Slider:GetEffectiveAlpha() end
function Slider:GetEffectiveDepth() end
function Slider:GetEffectiveScale() end
function Slider:GetFrameLevel() end
function Slider:GetFrameStrata() end
function Slider:GetHeight() end
function Slider:GetHitRectInsets() end
function Slider:GetID() end
function Slider:GetLeft() end
function Slider:GetMaxResize() end
function Slider:GetMinMaxValues() end
function Slider:GetMinResize() end
function Slider:GetName() end
function Slider:GetNumChildren() end
function Slider:GetNumPoints() end
function Slider:GetNumRegions() end
function Slider:GetObjectType() end
function Slider:GetOrientation() end
function Slider:GetParent() end
function Slider:GetPropagateKeyboardInput() end
function Slider:GetRect() end
function Slider:GetRegions() end
function Slider:GetRight() end
function Slider:GetScale() end
function Slider:GetSize() end
function Slider:GetThumbTexture() end
function Slider:GetTitleRegion() end
function Slider:GetTop() end
function Slider:GetValue() end
function Slider:GetValueStep() end
function Slider:GetWidth() end
function Slider:Hide() end
function Slider:IsClampedToScreen() end
function Slider:IsDragging() end
function Slider:IsEnabled() end
function Slider:IsIgnoringDepth() end
function Slider:IsJoystickEnabled() end
function Slider:IsKeyboardEnabled() end
function Slider:IsMouseEnabled() end
function Slider:IsMouseWheelEnabled() end
function Slider:IsMovable() end
function Slider:IsProtected() end
function Slider:IsResizable() end
function Slider:IsShown() end
function Slider:IsToplevel() end
function Slider:IsUserPlaced() end
function Slider:IsVisible() end
function Slider:Lower() end
function Slider:Raise() end
function Slider:RegisterAllEvents() end
function Slider:SetDontSavePosition() end
function Slider:SetPropagateKeyboardInput() end
function Slider:Show() end
function Slider:StartMoving() end
function Slider:StartSizing() end
function Slider:StopAnimating() end
function Slider:StopMovingOrSizing() end
function Slider:UnregisterAllEvents() end

---@class StatusBar
StatusBar = {}

---SetMinMaxValues
---@param minValue number
---@param maxValue number
function SetMinMaxValues:SetMinMaxValues(minValue, maxValue) end

function StatusBar:AllowAttributeChanges() end
function StatusBar:CanChangeAttribute() end
function StatusBar:CanChangeProtectedState() end
function StatusBar:ClearAllPoints() end
function StatusBar:CreateTitleRegion() end
function StatusBar:GetAlpha() end
function StatusBar:GetAnimationGroups() end
function StatusBar:GetBackdrop() end
function StatusBar:GetBackdropBorderColor() end
function StatusBar:GetBackdropColor() end
function StatusBar:GetBottom() end
function StatusBar:GetBoundsRect() end
function StatusBar:GetCenter() end
function StatusBar:GetChildren() end
function StatusBar:GetClampRectInsets() end
function StatusBar:GetDepth() end
function StatusBar:GetDontSavePosition() end
function StatusBar:GetEffectiveAlpha() end
function StatusBar:GetEffectiveDepth() end
function StatusBar:GetEffectiveScale() end
function StatusBar:GetFrameLevel() end
function StatusBar:GetFrameStrata() end
function StatusBar:GetHeight() end
function StatusBar:GetHitRectInsets() end
function StatusBar:GetID() end
function StatusBar:GetLeft() end
function StatusBar:GetMaxResize() end
function StatusBar:GetMinMaxValues() end
function StatusBar:GetMinResize() end
function StatusBar:GetName() end
function StatusBar:GetNumChildren() end
function StatusBar:GetNumPoints() end
function StatusBar:GetNumRegions() end
function StatusBar:GetObjectType() end
function StatusBar:GetOrientation() end
function StatusBar:GetParent() end
function StatusBar:GetPropagateKeyboardInput() end
function StatusBar:GetRect() end
function StatusBar:GetRegions() end
function StatusBar:GetRight() end
function StatusBar:GetRotatesTexture() end
function StatusBar:GetScale() end
function StatusBar:GetSize() end
function StatusBar:GetStatusBarColor() end
function StatusBar:GetStatusBarTexture() end
function StatusBar:GetTitleRegion() end
function StatusBar:GetTop() end
function StatusBar:GetValue() end
function StatusBar:GetWidth() end
function StatusBar:Hide() end
function StatusBar:IsClampedToScreen() end
function StatusBar:IsDragging() end
function StatusBar:IsIgnoringDepth() end
function StatusBar:IsJoystickEnabled() end
function StatusBar:IsKeyboardEnabled() end
function StatusBar:IsMouseEnabled() end
function StatusBar:IsMouseWheelEnabled() end
function StatusBar:IsMovable() end
function StatusBar:IsProtected() end
function StatusBar:IsResizable() end
function StatusBar:IsShown() end
function StatusBar:IsToplevel() end
function StatusBar:IsUserPlaced() end
function StatusBar:IsVisible() end
function StatusBar:Lower() end
function StatusBar:Raise() end
function StatusBar:RegisterAllEvents() end
function StatusBar:SetDontSavePosition() end
function StatusBar:SetPropagateKeyboardInput() end
function StatusBar:Show() end
function StatusBar:StartMoving() end
function StatusBar:StartSizing() end
function StatusBar:StopAnimating() end
function StatusBar:StopMovingOrSizing() end
function StatusBar:UnregisterAllEvents() end
function TabardModel:AdvanceTime() end
function TabardModel:AllowAttributeChanges() end
function TabardModel:CanChangeAttribute() end
function TabardModel:CanChangeProtectedState() end
function TabardModel:CanSaveTabardNow() end
function TabardModel:ClearAllPoints() end
function TabardModel:ClearFog() end
function TabardModel:ClearModel() end
function TabardModel:CreateTitleRegion() end
function TabardModel:GetAlpha() end
function TabardModel:GetAnimationGroups() end
function TabardModel:GetBackdrop() end
function TabardModel:GetBackdropBorderColor() end
function TabardModel:GetBackdropColor() end
function TabardModel:GetBottom() end
function TabardModel:GetBoundsRect() end
function TabardModel:GetCenter() end
function TabardModel:GetChildren() end
function TabardModel:GetClampRectInsets() end
function TabardModel:GetDepth() end
function TabardModel:GetDontSavePosition() end
function TabardModel:GetEffectiveAlpha() end
function TabardModel:GetEffectiveDepth() end
function TabardModel:GetEffectiveScale() end
function TabardModel:GetFacing() end
function TabardModel:GetFogColor() end
function TabardModel:GetFogFar() end
function TabardModel:GetFogNear() end
function TabardModel:GetFrameLevel() end
function TabardModel:GetFrameStrata() end
function TabardModel:GetHeight() end
function TabardModel:GetHitRectInsets() end
function TabardModel:GetID() end
function TabardModel:GetLeft() end
function TabardModel:GetLight() end
function TabardModel:GetMaxResize() end
function TabardModel:GetMinResize() end
function TabardModel:GetModel() end
function TabardModel:GetModelScale() end
function TabardModel:GetName() end
function TabardModel:GetNumChildren() end
function TabardModel:GetNumPoints() end
function TabardModel:GetNumRegions() end
function TabardModel:GetObjectType() end
function TabardModel:GetParent() end
function TabardModel:GetPosition() end
function TabardModel:GetPropagateKeyboardInput() end
function TabardModel:GetRect() end
function TabardModel:GetRegions() end
function TabardModel:GetRight() end
function TabardModel:GetScale() end
function TabardModel:GetSize() end
function TabardModel:GetTitleRegion() end
function TabardModel:GetTop() end
function TabardModel:GetWidth() end
function TabardModel:Hide() end
function TabardModel:InitializeTabardColors() end
function TabardModel:IsClampedToScreen() end
function TabardModel:IsDragging() end
function TabardModel:IsIgnoringDepth() end
function TabardModel:IsJoystickEnabled() end
function TabardModel:IsKeyboardEnabled() end
function TabardModel:IsMouseEnabled() end
function TabardModel:IsMouseWheelEnabled() end
function TabardModel:IsMovable() end
function TabardModel:IsProtected() end
function TabardModel:IsResizable() end
function TabardModel:IsShown() end
function TabardModel:IsToplevel() end
function TabardModel:IsUserPlaced() end
function TabardModel:IsVisible() end
function TabardModel:Lower() end
function TabardModel:Raise() end
function TabardModel:RefreshCamera() end
function TabardModel:RefreshUnit() end
function TabardModel:RegisterAllEvents() end
function TabardModel:Save() end
function TabardModel:SetBarberShopAlternateForm() end
function TabardModel:SetCamDistanceScale() end
function TabardModel:SetDisplayInfo() end
function TabardModel:SetDontSavePosition() end
function TabardModel:SetPortraitZoom() end
function TabardModel:SetPropagateKeyboardInput() end
function TabardModel:Show() end
function TabardModel:StartMoving() end
function TabardModel:StartSizing() end
function TabardModel:StopAnimating() end
function TabardModel:StopMovingOrSizing() end
function TabardModel:UnregisterAllEvents() end
function Texture:CanChangeProtectedState() end
function Texture:ClearAllPoints() end
function Texture:GetAlpha() end
function Texture:GetAnimationGroups() end
function Texture:GetBlendMode() end
function Texture:GetBottom() end
function Texture:GetCenter() end
function Texture:GetDrawLayer() end
function Texture:GetHeight() end
function Texture:GetHorizTile() end
function Texture:GetLeft() end
function Texture:GetName() end
function Texture:GetNonBlocking() end
function Texture:GetNumPoints() end
function Texture:GetObjectType() end
function Texture:GetParent() end
function Texture:GetRect() end
function Texture:GetRight() end
function Texture:GetSize() end
function Texture:GetTexCoord() end
function Texture:GetTexture() end
function Texture:GetTop() end
function Texture:GetVertTile() end
function Texture:GetVertexColor() end
function Texture:GetWidth() end
function Texture:Hide() end
function Texture:IsDesaturated() end
function Texture:IsDragging() end
function Texture:IsProtected() end
function Texture:IsShown() end
function Texture:IsVisible() end
function Texture:SetHorizTile() end
function Texture:SetVertTile() end
function Texture:Show() end
function Texture:StopAnimating() end
function Translation:GetDuration() end
function Translation:GetElapsed() end
function Translation:GetEndDelay() end
function Translation:GetMaxFramerate() end
function Translation:GetName() end
function Translation:GetObjectType() end
function Translation:GetOffset() end
function Translation:GetOrder() end
function Translation:GetParent() end
function Translation:GetProgress() end
function Translation:GetProgressWithDelay() end
function Translation:GetRegionParent() end
function Translation:GetSmoothProgress() end
function Translation:GetSmoothing() end
function Translation:GetStartDelay() end
function Translation:IsDelaying() end
function Translation:IsDone() end
function Translation:IsPaused() end
function Translation:IsPlaying() end
function Translation:IsStopped() end
function Translation:Pause() end
function Translation:Play() end
function Translation:SetSmoothProgress() end
function Translation:Stop() end
function UIObject:GetName() end
function UIObject:GetObjectType() end
function VisibleRegion:CanChangeProtectedState() end
function VisibleRegion:ClearAllPoints() end
function VisibleRegion:GetAlpha() end
function VisibleRegion:GetAnimationGroups() end
function VisibleRegion:GetBottom() end
function VisibleRegion:GetCenter() end
function VisibleRegion:GetHeight() end
function VisibleRegion:GetLeft() end
function VisibleRegion:GetName() end
function VisibleRegion:GetNumPoints() end
function VisibleRegion:GetObjectType() end
function VisibleRegion:GetParent() end
function VisibleRegion:GetRect() end
function VisibleRegion:GetRight() end
function VisibleRegion:GetSize() end
function VisibleRegion:GetTop() end
function VisibleRegion:GetWidth() end
function VisibleRegion:Hide() end
function VisibleRegion:IsDragging() end
function VisibleRegion:IsProtected() end
function VisibleRegion:IsShown() end
function VisibleRegion:IsVisible() end
function VisibleRegion:Show() end
function VisibleRegion:StopAnimating() end