---@class BagIndex : Enum
---@field Bankbag BagIndex @ -4
---@field Reagentbank BagIndex @ -3
---@field Keyring BagIndex @ -2
---@field Bank BagIndex @ -1
---@field Backpack BagIndex @ 0
---@field Bag_1 BagIndex @ 1
---@field Bag_2 BagIndex @ 2
---@field Bag_3 BagIndex @ 3
---@field Bag_4 BagIndex @ 4
---@field ReagentBag BagIndex @ 5
---@field BankBag_1 BagIndex @ 6
---@field BankBag_2 BagIndex @ 7
---@field BankBag_3 BagIndex @ 8
---@field BankBag_4 BagIndex @ 9
---@field BankBag_5 BagIndex @ 10
---@field BankBag_6 BagIndex @ 11
---@field BankBag_7 BagIndex @ 12
---@type BagIndex 
Enum.BagIndex = {}

